### ISSUE TITLE
Use genre field for category and attributes.

### ISSUE THREAD

**Issue by mxrlkn** [Ryan0751/QuickTag#2]
Just saw your software on digitaltechtools and it seems to have lots of potential.

A lot of dj's only use the genre tag for multiple genre's. A option to use only that field would be great. And an option to create as many "attributes/categories" as you like would be great to.

I would like to help but I don't make software. If you need a small website for Quicktag on a github page I would be happy to make that :)

**Comment by Ryan0751** [comment]
You can currently create up to 8 categories, and 16 attributes, and as many genres as you like.  I think that should be enough!  Additional ones are possible, the the limit isn't arbitrary because of how apple script/objective c work.

I can look into an option for putting the data into the genre field.  This does sort of violate the ID3v2 standard, however.  Comments are more appropriate for arbitrary meta-data, particularly of length.

Please keep in mind that the current scope of the project is to provide a means for DJ's to easily tag their music, within the confines of the defined tag system.  It would be difficult to accommodate all existing DJ's tag formats, there is simply too many combinations.

**Comment by mxrlkn** [comment]
Okay great. Maybe I should switch to using the comment field instead then. Thanks for the reply.

**Comment by Ryan0751** [comment]
After exploration, I will be providing options for prepend and append for comments, but not putting the large values into the genre field.
